title:            Riley F. Edmunds
description:      Undergraduate at UC Berkeley
url:              #blank
signoff:          Riley F. Edmunds
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /
  - name:         Ideas
    url:          /ideas
    external:     false
  - name:         LinkedIn
    url:          http://linkedin.com/in/rileyedmunds
    external:     true
    target:       _blank
  - name:         GitHub
    url:          http://github.com/rileyedmunds
    external:     true
    target:       _blank
highlighter:      rouge
permalink:        pretty
# markdown:         redcarpet
redcarpet:
  extensions:
    - smart

gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
